name: Setup RDP on Debian

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget tasksel

      - name: Install Chrome Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo dpkg --install chrome-remote-desktop_current_amd64.deb || sudo apt install -y --fix-broken

      - name: Install XFCE Desktop Environment
        run: |
          sudo apt install -y xfce4 xfce4-terminal desktop-base xscreensaver
          echo "exec /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg --install google-chrome-stable_current_amd64.deb || sudo apt install -y --fix-broken

      - name: Set Up Chrome Remote Desktop
        env:
          CRP_COMMAND: ${{ secrets.CRP_COMMAND }}
          RDP_PIN: ${{ secrets.RDP_PIN }}
        run: |
          if [[ -z "$CRP_COMMAND" || -z "$RDP_PIN" ]]; then
            echo "Error: CRP_COMMAND and RDP_PIN secrets must be set in the repository."
            exit 1
          fi

          # Execute CRP setup command
          eval "$CRP_COMMAND --pin=$RDP_PIN"

          # Start Chrome Remote Desktop Service
          sudo service chrome-remote-desktop start

          echo "RDP setup complete. Access it via https://remotedesktop.google.com/access."
