name: Temporary Linux VPS with AnyDesk

on:
  workflow_dispatch:

jobs:
  setup-anydesk:
    runs-on: ubuntu-latest

    steps:
      - name: Install Prerequisites
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y wget gnupg2 curl software-properties-common

      - name: Install AnyDesk
        run: |
          wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo apt-key add -
          echo "deb http://deb.anydesk.com/ all main" | sudo tee /etc/apt/sources.list.d/anydesk.list
          sudo apt update
          sudo apt install -y anydesk || exit 1

      - name: Start AnyDesk Service
        run: |
          sudo systemctl restart anydesk.service
          sudo systemctl status anydesk.service

      - name: Display AnyDesk Address
        run: |
          echo "AnyDesk installed. Use the AnyDesk address below to connect:"
          anydesk --get-id || echo "Failed to retrieve AnyDesk ID. Check logs above."

      - name: Debug Information
        run: |
          sudo systemctl status anydesk.service
          sudo journalctl -u anydesk.service
