name: Debian Linux with GRD

on:
  workflow_dispatch:  

jobs:
  setup-grd:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Required Packages
        run: |
          sudo apt update
          sudo apt install -y wget tasksel

      - name: Install XFCE Desktop Environment
        run: |
          sudo tasksel install xfce-desktop

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y

      - name: Install Google Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt-get install -f -y

      - name: Enable Chrome Remote Desktop
        run: |
          sudo systemctl enable chrome-remote-desktop
          sudo systemctl start chrome-remote-desktop

      - name: Link to GRD
        run: |
         DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AanRRrtDBAaMiuhKMAfX8bsI3atipLKsa1bkTzFRzo-Mox4-rgBtRwF32hJiMqI9jLWEMw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)


      - name: Link GRD to Your Google Account
        run: |
          echo "Visit https://remotedesktop.google.com/headless to generate the setup command for Debian Linux."
          echo "Copy and run the command below in a terminal session."

      - name: Keep the Workflow Active
        run: |
          echo "Workflow is running. Do not close this session."
          while true; do sleep 60; done
